version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=my_flask_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres  
    ports:
      - '5432:5432'

  flask:
    image: flask_app
    ports:
        - 5000:5000
    volumes:
        - .:/app
    depends_on:
      - postgres
